# Numpy Tutorial

In [64]:
# Import numpy, conventionally as "np"
import numpy as np
# Numpy enables creation of N-dimensional arrays of data, or ndarrays
a=np.array([2,3,4,5])
b=np.array((5,6,7,8))
print type(a)
print "a -->", a
print "b -->", b
print "a+b -->", a+b

 <type 'numpy.ndarray'>
a --> [2 3 4 5]
b --> [5 6 7 8]
a+b --> [ 7  9 11 13]


In [5]:
# We can get the shape of the array, which is a tuple of the sizes of its dimensions
print(a.shape)

(4,)


In [66]:
z=np.zeros(10)
print(z)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [67]:
print(z.shape)

(10,)


In [68]:
print(z.ndim)

1


In [14]:
# If we had an 2*5 ndarray, and we can intialize with "zeros" or "ones":
x=np.zeros([2, 5])
print(x)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [15]:
print(x.shape)
print(x.ndim)

(2, 5)
2


In [16]:
# Or we can initialize with a shape of 4, 9:
x=np.zeros([4, 9])
print(x)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [17]:
print(x.shape)
print(x.ndim)

(4, 9)
2


In [20]:
# We can also create an array of > 2 dimensions
# Consider the following from the documentation of scipy: https://docs.scipy.org/doc/numpy-dev/user/quickstart.html:
"""
When you print an array, NumPy displays it in a similar way to nested lists, but with the following layout:

    the last axis is printed from left to right,
    the second-to-last is printed from top to bottom,
    the rest are also printed from top to bottom, with each slice separated from the next by an empty line.

One-dimensional arrays are then printed as rows, bidimensionals as matrices and tridimensionals as lists of matrices.
"""
x=np.ones([2, 4, 3])
print(x)

[[[ 1.  1.  1.]
  [ 1.  1.  1.]
  [ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]
  [ 1.  1.  1.]
  [ 1.  1.  1.]]]


In [21]:
print(x.shape)
print(x.ndim)

(2, 4, 3)
3


In [39]:
x=np.zeros([2, 3, 4, 5])
print(x)

[[[[ 0.  0.  0.  0.  0.]
   [ 0.  0.  0.  0.  0.]
   [ 0.  0.  0.  0.  0.]
   [ 0.  0.  0.  0.  0.]]

  [[ 0.  0.  0.  0.  0.]
   [ 0.  0.  0.  0.  0.]
   [ 0.  0.  0.  0.  0.]
   [ 0.  0.  0.  0.  0.]]

  [[ 0.  0.  0.  0.  0.]
   [ 0.  0.  0.  0.  0.]
   [ 0.  0.  0.  0.  0.]
   [ 0.  0.  0.  0.  0.]]]


 [[[ 0.  0.  0.  0.  0.]
   [ 0.  0.  0.  0.  0.]
   [ 0.  0.  0.  0.  0.]
   [ 0.  0.  0.  0.  0.]]

  [[ 0.  0.  0.  0.  0.]
   [ 0.  0.  0.  0.  0.]
   [ 0.  0.  0.  0.  0.]
   [ 0.  0.  0.  0.  0.]]

  [[ 0.  0.  0.  0.  0.]
   [ 0.  0.  0.  0.  0.]
   [ 0.  0.  0.  0.  0.]
   [ 0.  0.  0.  0.  0.]]]]


In [40]:
print(x.shape)
print(x.ndim)

(2, 3, 4, 5)
4


In [22]:
print(x.dtype)

float64


In [42]:
# Note array data type...
x=np.ones([2, 4, 3], dtype=np.int32)
print(x)
print(x.dtype)

[[[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]]
int32


## Operations on arrays:

In [43]:
print(x*5)

[[[5 5 5]
  [5 5 5]
  [5 5 5]
  [5 5 5]]

 [[5 5 5]
  [5 5 5]
  [5 5 5]
  [5 5 5]]]


In [44]:
print(x/5.0)

[[[ 0.2  0.2  0.2]
  [ 0.2  0.2  0.2]
  [ 0.2  0.2  0.2]
  [ 0.2  0.2  0.2]]

 [[ 0.2  0.2  0.2]
  [ 0.2  0.2  0.2]
  [ 0.2  0.2  0.2]
  [ 0.2  0.2  0.2]]]


In [45]:
# We can slice
my_slice=x[1:2]
print(my_slice)

[[[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]]


In [3]:
# You can only add arrays of the same shape / equal length:
c=np.array([5,8,8,9,5,2])
# print "This will give an error if you print it!!!"
# print "a+c -->", a+c

In [51]:
# broadcasting
# If you add an array to a scalar, the scalar gets broadcast across all the array elements
print "a -->", a
print "a+1 -->", a+2
# Now you can broadcast arrays and so you can add arrays of different shapes...

a --> [2 3 4 5]
a+1 --> [4 5 6 7]


In [52]:
x= np.array([[1, 2, 3, 4], [5, 6, 7, 8]], dtype=np.float32)
print "Printing array x: ", x,"\n"
print "\"Shape of array x is:\" ", x.shape,"\n"
print "\"Value at x[0][1] is:\" ", x[0][1] # gives row0, c1  --> we start index from zero!

Printing array x:  [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]] 

"Shape of array x is:"  (2, 4) 

"Value at x[0][1] is:"  2.0


## More operations

In [53]:
x=np.array([1, 3, 5, 6])
y=np.array([1,2,3,1])
d=y[1:]-y[:-1]
print d
# This runs in C, the loop happens in C, so it's fast.
# It doesn't matter what shape y is. So, it can be a very big array.

[ 1  1 -2]


In [55]:
print(x*y)

[ 1  6 15  6]


In [57]:
# You cannot do the below:
# You will get an error:
# ValueError: operands could not be broadcast together with shapes (4,) (5,)
x=np.array([1, 3, 5, 6])
y=np.array([1,2,3,1, 9])
d=y[1:]-y[:-1]
print(x*y)

In [59]:
print sum(a)
# cumsum adds every emelement to the previous element
print np.cumsum(a)

14
[ 2  5  9 14]


In [61]:
#numpy.arange: http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html
"""
numpy.arange([start, ]stop, [step, ]dtype=None)
    Return evenly spaced values within a given interval.
    Values are generated within the half-open interval [start, stop) (in other words, the interval including
    start but excluding stop). For integer arguments the function is equivalent to the Python built-in range
    function, but returns an ndarray rather than a list.
"""
print "-------------------"
print np.arange(3)
print np.arange(3.0)
print "-------------------"
print np.arange(2,7)
print "-------------------"
print np.arange(2,50, 5)
print "-------------------"

-------------------
[0 1 2]
[ 0.  1.  2.]
-------------------
[2 3 4 5 6]
-------------------
[ 2  7 12 17 22 27 32 37 42 47]
-------------------


In [5]:
#------------------
print "numpy.zeros"
#------------------
"""
 numpy.zeros(shape, dtype=float, order='C')¶
    Return a new array of given shape and type, filled with zeros.
    
shape : int or sequence of ints
    Shape of the new array, e.g., (2, 3) or 2.
"""
print "-------------------"
print np.zeros(5)
print "-------------------"
print np.zeros((10,), dtype=np.int)
print "-------------------"
print np.zeros((3, 1))
print "-------------------"
#------------------
print "numpy.ones"
#------------------
"""
 numpy.ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
"""
print "-------------------"
print np.ones(5)
print "-------------------"
print np.ones((10,), dtype=np.float128)
print "-------------------"
print np.ones((3, 1))
print "-------------------"

#------------------
print "numpy.identity"
#------------------
"""
 numpy.identity(n, dtype=None)
    Return the identity array.
    The identity array is a square array with ones on the main diagonal.
n : int
    Number of rows (and columns) in n x n output.
"""
print "-------------------"
print np.identity(5)
print "-------------------"


 numpy.zeros
-------------------
[ 0.  0.  0.  0.  0.]
-------------------
[0 0 0 0 0 0 0 0 0 0]
-------------------
[[ 0.]
 [ 0.]
 [ 0.]]
-------------------
numpy.ones
-------------------
[ 1.  1.  1.  1.  1.]
-------------------
[ 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0]
-------------------
[[ 1.]
 [ 1.]
 [ 1.]]
-------------------
numpy.identity
-------------------
[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]
-------------------


In [52]:
#------------------
print "\n numpy.linspace"
#------------------
"""
 numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)[source]
    Return evenly spaced numbers over a specified interval.
    Returns num evenly spaced samples, calculated over the interval [start, stop].
    The endpoint of the interval can optionally be excluded.
    
retstep : bool, optional
    If True, return (samples, step), where step is the spacing between samples.

http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.linspace.html#numpy.linspace
"""
print np.linspace(2.0, 3.0, num=5)
print "-------------------"
print np.linspace(2.0, 3.0, num=5, endpoint=False)
print "-------------------"
print np.linspace(2.0, 3.0, num=5, retstep=True)
print "-------------------\n"
#------------------
print "\n numpy.logspace"
#------------------
"""
 numpy.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)
    Return numbers spaced evenly on a log scale.
    In linear space, the sequence starts at base ** start (base to the power of start) 
    and ends with base ** stop (see endpoint below).
"""
print "-------------------"*3
print np.logspace(2.0, 3.0, num=4)
print "-------------------"*3
print np.logspace(2.0, 3.0, base=2.0, num=4)
print "-------------------"*3
print np.logspace(2.0, 3.0, base=2.0, num=4, endpoint=False)
print "-------------------"*3


 numpy.linspace
[ 2.    2.25  2.5   2.75  3.  ]
-------------------
[ 2.   2.2  2.4  2.6  2.8]
-------------------
(array([ 2.  ,  2.25,  2.5 ,  2.75,  3.  ]), 0.25)
-------------------


 numpy.logspace
---------------------------------------------------------
[  100.           215.443469     464.15888336  1000.        ]
---------------------------------------------------------
[ 4.          5.0396842   6.34960421  8.        ]
---------------------------------------------------------
[ 4.          4.75682846  5.65685425  6.72717132]
---------------------------------------------------------
