# Numpy Tutorial

In [3]:
from numpy import *
#from numpy import array
import numpy as np
a= array([2,3,4,5])
b=array((5,6,7,8))
print type(a)
print "a -->", a
print "b -->", b
print "a+b -->", a+b


<type 'numpy.ndarray'>
a --> [2 3 4 5]
b --> [5 6 7 8]
a+b --> [ 7  9 11 13]


In [4]:
# You can only add arrays of the same shape / equal length:
c=array([5,8,8,9,5,2])
print "This will give an error!!!"
print "a+c -->", a+c

This will give an error!!!
a+c -->

ValueError: operands could not be broadcast together with shapes (4,) (6,) 

In [19]:
# broadcasting
# If you add an array to a scalar, the scalar gets broadcast across all the array elements
print "a+1 -->", a+1
# Now you can broadcast arrays and so you can add arrays of different shapes...

a+1 --> [3 4 5 6]


In [6]:
import numpy as np
x= np.array([[1, 2, 3, 4], [5, 6, 7, 8]], dtype=np.float32)
print "Printing array x: ", x,"\n"
print "\"Shape of array x is:\" ", x.shape,"\n"
print "\"Value at x[0][1] is:\" ", x[0][1] # gives row0, c1  --> we start index from zero!

Printing array x:  [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]] 

"Shape of array x is:"  (2, 4) 

"Value at x[0][1] is:"  2.0


In [7]:
x=np.array([1, 3, 5, 6])
y=np.array([1,2,3,1])
d=y[1:]-y[:-1]
print d
# This runs in C, the loop happens in C, so it's fast.
# It doesn't matter what shape y is. So, it can be a very big array.

[ 1  1 -2]


In [8]:
print sum(a)
# cumsum adds every emelement to the previous element
print cumsum(a)

14
[ 2  5  9 14]


In [35]:
import numpy as np
#numpy.arange: http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html
"""
numpy.arange([start, ]stop, [step, ]dtype=None)
    Return evenly spaced values within a given interval.
    Values are generated within the half-open interval [start, stop) (in other words, the interval including
    start but excluding stop). For integer arguments the function is equivalent to the Python built-in range
    function, but returns an ndarray rather than a list.
"""
print "-------------------"
print np.arange(3)
print np.arange(3.0)
print "-------------------"
print np.arange(2,7)
print "-------------------"
print np.arange(2,7, 2)
print "-------------------"

-------------------
[0 1 2]
[ 0.  1.  2.]
-------------------
[2 3 4 5 6]
-------------------
[2 4 6]
-------------------
[  100.           215.443469     464.15888336  1000.        ]


In [5]:
import numpy as np
#------------------
print "numpy.zeros"
#------------------
"""
 numpy.zeros(shape, dtype=float, order='C')¶
    Return a new array of given shape and type, filled with zeros.
    
shape : int or sequence of ints
    Shape of the new array, e.g., (2, 3) or 2.
"""
print "-------------------"
print np.zeros(5)
print "-------------------"
print np.zeros((10,), dtype=np.int)
print "-------------------"
print np.zeros((3, 1))
print "-------------------"
#------------------
print "numpy.ones"
#------------------
"""
 numpy.ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
"""
print "-------------------"
print np.ones(5)
print "-------------------"
print np.ones((10,), dtype=np.float128)
print "-------------------"
print np.ones((3, 1))
print "-------------------"

#------------------
print "numpy.identity"
#------------------
"""
 numpy.identity(n, dtype=None)
    Return the identity array.
    The identity array is a square array with ones on the main diagonal.
n : int
    Number of rows (and columns) in n x n output.
"""
print "-------------------"
print np.identity(5)
print "-------------------"


 numpy.zeros
-------------------
[ 0.  0.  0.  0.  0.]
-------------------
[0 0 0 0 0 0 0 0 0 0]
-------------------
[[ 0.]
 [ 0.]
 [ 0.]]
-------------------
numpy.ones
-------------------
[ 1.  1.  1.  1.  1.]
-------------------
[ 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0]
-------------------
[[ 1.]
 [ 1.]
 [ 1.]]
-------------------
numpy.identity
-------------------
[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]
-------------------


In [52]:
import numpy as np
#------------------
print "\n numpy.linspace"
#------------------
"""
 numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)[source]¶
    Return evenly spaced numbers over a specified interval.
    Returns num evenly spaced samples, calculated over the interval [start, stop].
    The endpoint of the interval can optionally be excluded.
    
retstep : bool, optional
    If True, return (samples, step), where step is the spacing between samples.

http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.linspace.html#numpy.linspace
"""
print np.linspace(2.0, 3.0, num=5)
print "-------------------"
print np.linspace(2.0, 3.0, num=5, endpoint=False)
print "-------------------"
print np.linspace(2.0, 3.0, num=5, retstep=True)
print "-------------------\n"
#------------------
print "\n numpy.logspace"
#------------------
"""
 numpy.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)
    Return numbers spaced evenly on a log scale.
    In linear space, the sequence starts at base ** start (base to the power of start) 
    and ends with base ** stop (see endpoint below).
"""
print "-------------------"*3
print np.logspace(2.0, 3.0, num=4)
print "-------------------"*3
print np.logspace(2.0, 3.0, base=2.0, num=4)
print "-------------------"*3
print np.logspace(2.0, 3.0, base=2.0, num=4, endpoint=False)
print "-------------------"*3


 numpy.linspace
[ 2.    2.25  2.5   2.75  3.  ]
-------------------
[ 2.   2.2  2.4  2.6  2.8]
-------------------
(array([ 2.  ,  2.25,  2.5 ,  2.75,  3.  ]), 0.25)
-------------------


 numpy.logspace
---------------------------------------------------------
[  100.           215.443469     464.15888336  1000.        ]
---------------------------------------------------------
[ 4.          5.0396842   6.34960421  8.        ]
---------------------------------------------------------
[ 4.          4.75682846  5.65685425  6.72717132]
---------------------------------------------------------
